// Folk Calm — Shared article data.
// Loaded BEFORE components.js and main.js (both use `defer`, which preserves
// document order, so this global is available by the time they run).
//
//   articles:     full editorial metadata — { url, title, desc, img, date, keywords }
//                 Used by components.js for Related Articles, Latest Articles,
//                 sidebar notes, and search.
//   staticPages:  search-only entries — { title, url, keywords }
//                 Non-article pages (index, categories, about, etc.) for main.js search.
window.FOLK_CALM_DATA = {
  articles: [
    { url: 'article-mugwort-foot-soak.html', title: 'Dried Mugwort and the Evening Foot Basin', desc: 'The herb seller tied dried mugwort with red cotton thread before placing it in my market bag. She pressed the bundle flat so the brittle leaves would not scatter among the vegetables.', img: 'images/warm-foot-soak-basin.webp', date: '2026-05-10', keywords: 'dried mugwort, Chinese household custom, evening foot basin, Dragon Boat Festival, Folk Calm' },
    { url: 'article-ginger-tea.html', title: 'Ginger and Red Dates After Dinner', desc: 'After dinner my grandmother cleared the bowls, cut ginger on the board that still smelled of scallion, and dropped red dates into a small enamel pot. The first cup went to the family member still sitting at the table.', img: 'images/ginger-date-tea.webp', date: '2026-05-10', keywords: 'ginger red date drink, Chinese after dinner custom, kitchen tea history, Folk Calm' },
    { url: 'article-rice-congee.html', title: 'Plain Rice Congee and the Everyday Pot', desc: 'At the grain stall, I asked why two sacks of white rice carried different prices. The seller rubbed a few grains between her fingers, then told me which one her family used for the breakfast pot.', img: 'images/rice-congee-kitchen.webp', date: '2026-05-10', keywords: 'plain rice congee, Chinese household food, rice porridge history, everyday kitchen, Folk Calm' },
    { url: 'article-salt-warm-pack.html', title: 'The Coarse Salt Warming Bag', desc: 'My grandmother made her salt bag from a worn cotton pillowcase. On winter evenings she warmed the coarse crystals in the kitchen, tested the bundle against her wrist, and carried it to the chair beside the television.', img: 'images/salt-warm-pack.webp', date: '2026-05-10', keywords: 'coarse salt bag, Chinese household warmth, cloth warming custom, winter home object, Folk Calm' },
    { url: 'article-yam-millet-porridge.html', title: 'Yam and Millet in the Northern Porridge Pot', desc: 'A northern grain seller split a piece of dried yam to show me its chalky center, then swept yellow millet into a paper bag. At home, the two colors stayed distinct until the breakfast pot began to thicken.', img: 'images/yam-millet-porridge.webp', date: '2026-05-20', keywords: 'yam millet porridge, northern Chinese breakfast, Chinese yam food history, Folk Calm' },
    { url: 'article-sichuan-peppercorn-foot-soak.html', title: 'Sichuan Peppercorn in the Winter Foot Basin', desc: 'The spice seller recognized the peppercorns I did not want for cooking. She pushed the duller husks into a separate paper twist and told me they still belonged in a winter household.', img: 'images/sichuan-peppercorn-foot-soak.webp', date: '2026-05-20', keywords: 'Sichuan peppercorn foot basin, Chinese winter custom, warm water household practice, Folk Calm' },
    { url: 'article-sour-jujube-seed-tea.html', title: 'Sour Jujube Seeds at the Bedside', desc: 'The herb-shop assistant crushed a sour-jujube seed beneath a small brass weight, then folded the fragments into paper. I heard the dry shell break above the quieter traffic outside.', img: 'images/sour-jujube-seed-tea.webp', date: '2026-05-20', keywords: 'sour jujube seed history, suan zao ren, Chinese evening cup, household record, Folk Calm' },
    { url: 'article-post-meal-walk.html', title: 'The Evening Walk After the Meal', desc: 'The post-meal walk begins when bowls are cleared and chairs move back. It is usually slow, social, and close to home: a courtyard circuit, a lane to the corner, or a loop through an apartment compound.', img: 'images/post-meal-walk.webp', date: '2026-05-20', keywords: 'Chinese post meal walk, evening courtyard custom, household daily rhythm, Folk Calm' },
    { url: 'article-scallion-white-root.html', title: 'Scallion White in the Early-Cold Kitchen', desc: 'When a wet coat came through the kitchen door, my grandmother set aside the white ends of the scallions she was cutting for dinner. She rinsed the roots, put on a small pot, and moved the dry shoes nearer the chair.', img: 'images/scallion-white-root.webp', date: '2026-05-21', keywords: 'scallion white drink, Chinese kitchen custom, spring onion root, ginger household drink, Folk Calm' },
    { url: 'article-goji-berry-tea.html', title: 'Goji Berries in the Glass Tea Jar', desc: 'At the dried-fruit counter, the shopkeeper pinched a goji berry open to show me the seeds. I carried the red parcel home beside a glass tea jar, careful not to crush it under the heavier groceries.', img: 'images/goji-berry-tea-cup.jpg', date: '2026-05-21', keywords: 'goji berry tea history, Chinese glass tea jar, dried goji household use, Folk Calm' },
    { url: 'article-moxibustion-home.html', title: 'Moxa Smoke in the Winter Room', desc: 'The herb-shop clerk would not hand over a moxa roll without showing me the ash bowl. She set a ceramic dish on the counter, opened the window behind her, and cleared the paper packets away from the demonstration space.', img: 'images/moxibustion.webp', date: '2026-05-24', keywords: 'moxa stick history, Chinese household custom, mugwort smoke, winter room, Folk Calm' },
    { url: 'article-ginger-foot-soak.html', title: 'Ginger in the Winter Foot Basin', desc: 'The woman next door carried her own enamel basin into the corridor on cold evenings. I knew ginger was inside before I saw the slices because the steam brought the kitchen smell through the open doorway.', img: 'images/ginger-foot-soak.jpg', date: '2026-05-24', keywords: 'ginger foot basin, Chinese winter household custom, warm water practice, Folk Calm' },
    { url: 'article-winter-melon-tea.html', title: 'Winter Melon Tea on the Autumn Counter', desc: 'The preserved-fruit seller cut a dark slab of winter-melon sugar with a broad knife and wrapped it in waxed paper. I carried the sticky parcel home separately from the tea and grain.', img: 'images/winter-melon-tea.webp', date: '2026-05-25', keywords: 'winter melon tea history, dong gua cha, Chinese autumn drink, household kitchen record, Folk Calm' },
    { url: 'article-morning-warm-water.html', title: 'The First Cup of Warm Water', desc: 'Before the office lights were fully on, the night guard filled his enamel mug from the communal kettle. I stood beside him with my own cup while the first buses moved past the gate.', img: 'images/morning-warm-water.webp', date: '2026-05-30', keywords: 'morning warm water custom, Chinese kitchen thermos, enamel cup, daily household record, Folk Calm' },
    { url: 'article-rice-water-rinse.html', title: 'Rice Water Between Kitchen and Washroom', desc: 'The downstairs neighbor never poured the first cloudy rice water straight into the drain. I watched her carry the enamel bowl from the kitchen to the courtyard, where several household jobs were waiting for it.', img: 'images/rice-water-rinse.webp', date: '2026-06-09', keywords: 'rice water rinse history, Chinese household reuse, kitchen water custom, hair washing record, Folk Calm' },
    { url: 'article-bedding-airing.html', title: 'Bedding Across the Courtyard Rail', desc: 'Bedding airing belongs to the clear-weather calendar of the household. Quilts move from beds to rails, cotton is turned and tapped, and the room remains open until the fabric is carried back inside.', img: 'images/bedding-airing.webp', date: '2026-06-09', keywords: 'Chinese bedding airing, quilt sunning custom, bamboo beater, household laundry history, Folk Calm' },
    { url: 'article-post-lunch-pause.html', title: 'The Midday Rest After Lunch', desc: 'The tailor next door lowered his bamboo blind after lunch but never locked the shop. I could still hear the radio behind it while he rested on a narrow bench between the cutting table and the fabric shelves.', img: 'images/post-lunch-pause.webp', date: '2026-06-09', keywords: 'Chinese midday rest, post lunch pause, xie shang, household daily rhythm, Folk Calm' },
    { url: 'article-soap-pods.html', title: 'Soap Pods at the Wash Basin', desc: 'The market vendor cracked a dried soap pod with a short wooden mallet and opened the dark shell toward me. I could see the sticky interior before I understood why these pods once hung beside wash basins.', img: 'images/soap-pods-bowl.webp', date: '2026-06-20', keywords: 'Chinese soap pods, zao jiao history, Gleditsia sinensis, household washing custom, Folk Calm' },
    { url: 'article-mung-bean-soup.html', title: 'The Summer Pot of Mung Bean Soup', desc: 'At the neighborhood grain shop, the clerk keeps mung beans in a deep bin near the door. I watch her reject the split, dusty ones before she folds the green beans into a square paper parcel.', img: 'images/mung-bean-soup-bowl.webp', date: '2026-06-20', keywords: 'mung bean soup history, Chinese summer food, green bean soup, household kitchen record, Folk Calm' },
    { url: 'article-chrysanthemum-tea.html', title: 'Chrysanthemum Flowers in the Autumn Teacup', desc: 'The tea seller opened a glass jar and lifted one dried chrysanthemum by its stem. I watched the pale petals loosen over the counter before they ever reached a cup.', img: 'images/chrysanthemum-tea-cup.webp', date: '2026-06-20', keywords: 'chrysanthemum tea history, Chinese autumn drink, dried flower tea, household tea custom, Folk Calm' },
    { url: 'article-warm-towel-compress.html', title: 'The Warm Towel Folded Over the Eyes', desc: 'At the end of a long sewing afternoon, my aunt folded a warm towel into a narrow rectangle and laid it over her closed eyes. I sat across from her while the machine wheel slowed to a stop.', img: 'images/warm-towel-compress.webp', date: '2026-06-23', keywords: 'warm eye towel custom, Chinese evening household habit, cotton cloth warmth, Folk Calm' },
    { url: 'article-pear-water-night-cough.html', title: 'Snow Pear Water in the Night Kitchen', desc: 'When I was seven, my grandmother heard me coughing from the back room and went to the kitchen without turning on the ceiling light. The pear, the small pot, and the bowl she carried upstairs are the part I remember.', img: 'images/pear-water-night-cough.webp', date: '2026-06-25', keywords: 'snow pear water, Chinese kitchen custom, rock sugar pear, night kitchen, Folk Calm' },
    { url: 'article-sour-plum-drink.html', title: 'Sour Plum Drink in the Beijing Summer', desc: 'In my grandmother\'s Beijing courtyard, the sour-plum jar lived on the refrigerator door through July. She checked it before breakfast, and my grandfather drank from it standing beside the open door after bicycle work in the lane.', img: 'images/sour-plum-drink.webp', date: '2026-06-27', keywords: 'sour plum drink history, suan mei tang, Beijing summer drink, Chinese household record, Folk Calm' },
    { url: 'article-tremella-soup.html', title: 'Tremella Soup and the Long Simmer', desc: 'The dried-goods seller turns a tremella cluster over in her palm and points to its tight folds. I carry the brittle flower home in a paper box; by the time it reaches the pot, it occupies far more room.', img: 'images/tremella-soup.webp', date: '2026-06-29', keywords: 'tremella soup history, snow fungus dessert, Chinese sweet soup, household kitchen record, Folk Calm' },
    { url: 'article-ginger-scalp-rub.html', title: 'Fresh Ginger at the Dressing Table', desc: 'My grandmother kept a small knob of ginger beside the soap dish. After washing her hair, she cut a fresh face on it at the bathroom sink and leaned toward the mirror while I stood behind her.', img: 'images/ginger-scalp-rub.webp', date: '2026-06-30', keywords: 'ginger scalp custom, Chinese grooming history, dressing table objects, Folk Calm' },
    { url: 'article-longan-red-date-tea.html', title: 'Longan and Red Date Tea in the Women\'s Room', desc: 'At a women\'s gathering, I watched the host remove date stones before the cups reached the older guests. The longan shells had already been cleared into a small bowl beside the kettle.', img: 'images/longan-red-date-tea.webp', date: '2026-07-01', keywords: 'longan red date tea, Chinese women\'s household drink, dried fruit tea history, Folk Calm' },
    { url: 'article-salt-water-gargle.html', title: 'The Salt-Water Glass Beside the Toothbrush', desc: 'At my aunt\'s washbasin, a small glass stood apart from the drinking cups. I knew it by the cloudy salt mark near the base and by the way she rinsed it before putting the toothbrushes back.', img: 'images/salt-water-gargle.webp', date: '2026-07-02', keywords: 'salt water gargle custom, Chinese morning routine, household washing record, Folk Calm' },
    { url: 'article-bamboo-wife.html', title: 'The Bamboo Wife in the Summer Bed', desc: 'The bamboo wife was a hollow woven bolster placed on a summer bed. Its literary names are unusually elaborate, but the object itself was built for arms, knees, moving air, and a room arranged around humid weather.', img: 'images/bamboo-wife.webp', date: '2026-07-03', keywords: 'bamboo wife history, Chinese summer bedding, bamboo bolster, household object, Folk Calm' },
    { url: 'article-lotus-root-water.html', title: 'Lotus Root Water: The Pale Summer Sip', desc: 'Lotus root came home from the market with mud in its joints. My grandmother cleaned the holes with a chopstick, cut the best rounds for dinner, and put the small end pieces into a side pot of water.', img: 'images/lotus-root-water.webp', date: '2026-07-06', keywords: 'lotus root water, Chinese summer kitchen, lotus root drink history, household food record, Folk Calm' },
    { url: 'article-mint-cool-cloth.html', title: 'Fresh Mint Cloth by the Summer Door', desc: 'My grandmother kept mint in a cracked clay pot on the kitchen sill. On the hottest afternoons she rubbed the leaves between her palms, lowered a cotton cloth into an enamel basin, and left it by the shaded back door.', img: 'images/mint-cool-cloth.webp', date: '2026-07-07', keywords: 'fresh mint cloth, Chinese summer household, cool basin custom, potted mint, Folk Calm' },
    { url: 'article-black-sesame-walnut-paste.html', title: 'Black Sesame Walnut Paste: The Dark Sweet Bowl', desc: 'At a dried-goods counter, I can hear the sesame before I smell it: seeds running through a metal scoop, walnuts knocking against the scale, and the vendor folding both into paper for the same kitchen bowl.', img: 'images/black-sesame-walnut-paste.webp', date: '2026-07-08', keywords: 'black sesame walnut paste, Chinese sweet bowl, stone mortar kitchen, household food record, Folk Calm' },
    { url: 'article-cassia-seed-pillow.html', title: 'Cassia Seed Pillow: An Old Summer Bedroom Object', desc: 'At the herb stall, the vendor poured cassia seeds into a shallow metal dish and shook it near my ear. The dry rustle explained why this old pillow never behaved like cotton.', img: 'images/cassia-seed-pillow.webp', date: '2026-07-09', keywords: 'cassia seed pillow, Chinese summer bedroom, jue ming zi pillow, household object, Folk Calm' },
    { url: 'article-water-chestnut-sugarcane-water.html', title: 'Water Chestnut and Sugarcane in the Summer Pot', desc: 'A neighbor arrived with a dented pot and a length of sugarcane wrapped in newspaper. I cleared the kitchen table while she tipped water chestnuts into the sink and asked for the heavier knife.', img: 'images/water-chestnut-sugarcane-water.webp', date: '2026-07-10', keywords: 'water chestnut sugarcane water, southern Chinese summer drink, household kitchen record, Folk Calm' },
    { url: 'article-corn-silk-water.html', title: 'Corn Silk Water at the Edge of the Summer Stove', desc: 'My grandmother saved the clean silk from fresh corn, rinsed it in a white bowl, and kept a small covered pot beside the lunch stove.', img: 'images/corn-silk-water.webp', date: '2026-07-13', keywords: 'corn silk water, Chinese summer kitchen, fresh corn custom, household food record, Folk Calm' },
    { url: 'article-ginger-on-the-belly.html', title: 'Ginger Beneath the Folded Belly Cloth', desc: 'An older neighbor grated fresh ginger into a thin cotton square, folded the cloth inward, and tucked it beneath a loose nightshirt before bed.', img: 'images/ginger-on-the-belly.webp', date: '2026-07-14', keywords: 'ginger belly cloth, Chinese warmth custom, cotton kitchen square, household record, Folk Calm' },
    { url: 'article-honey-white-radish-water.html', title: 'Honey and White Radish in a Lidded Jar', desc: 'A wet-market seller chose a firm white radish, trimmed its leaves, and wrapped it in newspaper. At home, I set the cut pieces beneath honey in a lidded jar.', img: 'images/honey-white-radish-water.webp', date: '2026-07-15', keywords: 'honey white radish water, Chinese kitchen jar, market vegetable custom, household record, Folk Calm' },
    { url: 'article-potato-slices-forehead.html', title: 'Potato Slices and the Folded Handkerchief', desc: 'The older neighbor at the card table pushed her chair back, went to the kitchen, and returned with a paring knife and a peeled potato. She cut a broad slice, laid it across a forehead, and folded a cotton handkerchief over it.', img: 'images/potato-slices-forehead.webp', date: '2026-07-16', keywords: 'potato forehead cloth, Chinese summer custom, household handkerchief, Folk Calm' },
    { url: 'article-hawthorn-water.html', title: 'Hawthorn Water at the Dried-Fruit Counter', desc: 'The woman who ran the dried-fruit counter stored hawthorn slices in a wide glass jar. She held one ring toward the window, shook the loose seeds from the scoop, and folded the paper bag twice before handing it over.', img: 'images/hawthorn-water.webp', date: '2026-07-17', keywords: 'hawthorn water, Chinese dried fruit drink, hawthorn slice custom, Folk Calm' },
    { url: 'article-star-anise-water.html', title: 'Star Anise in the Winter Cup', desc: 'Every winter my grandmother\'s sister arrived with a small cloth bag of star anise. She said the town shop\'s stock was stale and placed her own jar beside my grandmother\'s on the kitchen shelf.', img: 'images/star-anise-water.webp', date: '2026-07-20', keywords: 'star anise water, Chinese winter cup, household spice custom, aunt family record, Folk Calm' },
    { url: 'article-hot-water-bottle.html', title: 'The Copper Hot Water Bottle', desc: 'My grandmother\'s hot water bottle was copper, with a screw cap tightened by hand. In winter it came out wrapped in old cotton cloth and was placed on the chair beside her bed each night.', img: 'images/hot-water-bottle.webp', date: '2026-07-21', keywords: 'copper hot water bottle, Chinese winter household, cloth warming custom, bedtime warmth, Folk Calm' },
    { url: 'article-walnut-rock-sugar-candy.html', title: 'Walnut Candy at the Kitchen Door', desc: 'My uncle was the one in the family who made walnut candy. He sat on a low stool at the kitchen door with a hammer and a cloth-wrapped block of rock sugar, while I crouched nearby waiting.', img: 'images/walnut-rock-sugar-candy.webp', date: '2026-07-22', keywords: 'walnut rock sugar candy, Chinese New Year sweet, uncle family recipe, kitchen wok candy, Folk Calm' },
    { url: 'article-salt-baked-orange.html', title: 'Salt Baked Orange at the Neighbor\'s Door', desc: 'On a winter night when I could not stop coughing, the downstairs neighbor knocked with a plate of two blackened oranges still steaming. She had cut a slit in each, filled it with salt, and baked them in the stove.', img: 'images/salt-baked-orange.webp', date: '2026-07-23', keywords: 'salt baked orange, Chinese winter cough remedy, neighbor custom, stove baked fruit, Folk Calm' },
    { url: 'article-lily-bulb-sweet-soup.html', title: 'Lily Bulb from the Herb Counter', desc: 'I went to the herb shop for fritillaria, but the woman behind the counter opened a different drawer and handed me dried lily bulb instead. She said it suited my grandmother better. She was not coughing, she was dry inside.', img: 'images/lily-bulb-sweet-soup.webp', date: '2026-07-24', keywords: 'lily bulb sweet soup, Chinese herb shop, dried lily bulb, grandmother heart calming, Folk Calm' },
  ],
  staticPages: [
    { title: 'Evening Foot Soak Tradition', url: 'index.html', keywords: 'foot soak evening basin warm water household practice' },
    { title: 'Categories - Folk Habits', url: 'categories.html', keywords: 'categories kitchen comforts compresses cloth warmth ginger tea' },
    { title: 'About Folk Calm', url: 'about.html', keywords: 'about cultural archive mission methodology' },
    { title: 'Disclaimer', url: 'disclaimer.html', keywords: 'disclaimer legal cultural record boundaries' },
    { title: 'Privacy Policy', url: 'privacy-policy.html', keywords: 'privacy gdpr ccpa data email policy' },
    { title: 'Affiliate Disclosure', url: 'affiliate-disclosure.html', keywords: 'affiliate disclosure transparency' },
    { title: 'Terms of Use', url: 'terms-of-use.html', keywords: 'terms of use legal policy' },
  ]
};
