var PAGE_HTML = [
'<!DOCTYPE html>',
'<html lang="en">',
'<head>',
'    <meta charset="UTF-8">',
'    <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">',
'    <title>Unsubscribe — Folk Calm</title>',
'    <meta name="description" content="Request removal from Folk Calm email updates.">',
'    <meta name="robots" content="noindex, nofollow">',
'    <link rel="icon" href="favicon.ico" type="image/x-icon">',
'    <link rel="stylesheet" href="css/styles.css">',
'    <script src="js/components.js?v=3" defer></script>',
'</head>',
'<body>',
'    <a href="#main" class="skip-link">Skip to main content</a>',
'    <div id="site-disclaimer-banner"></div>',
'    <div id="site-header"></div>',
'    <main id="main" class="wrap">',
'        <article>',
'            <h1>Unsubscribe</h1>',
'            <div id="unsubscribe-sent" style="display:none">',
'                <p class="lead">Your unsubscribe request has been received.</p>',
'                <p>We\'ll remove you from Folk Calm updates, usually within 24 hours. You won\'t receive further emails from us.</p>',
'                <p><a href="/">Back to the home page →</a></p>',
'            </div>',
'            <div id="unsubscribe-error" style="display:none">',
'                <p class="lead">Something went wrong. Please try again, or email us directly at <a href="mailto:unsubscribe@tcmwellness.xyz?subject=Unsubscribe">unsubscribe@tcmwellness.xyz</a>.</p>',
'            </div>',
'            <div id="unsubscribe-form">',
'                <p class="lead">Enter the email address you want removed from Folk Calm updates.</p>',
'                <form class="email-cta-form" action="/unsubscribe" method="post">',
'                    <input type="email" name="email_address" placeholder="Your email address" required aria-label="Email address">',
'                    <button type="submit">Send Unsubscribe Request</button>',
'                </form>',
'                <p class="privacy-note">You can also reply STOP to any Folk Calm email. Requests are processed within 24 hours.</p>',
'            </div>',
'        </article>',
'    </main>',
'    <div id="site-footer"></div>',
'    <script>',
'    (function(){',
'        var p=new URLSearchParams(window.location.search);',
'        if(p.get("sent")==="1"){document.getElementById("unsubscribe-form").style.display="none";document.getElementById("unsubscribe-sent").style.display="block"}',
'        else if(p.get("error")==="1"){document.getElementById("unsubscribe-form").style.display="none";document.getElementById("unsubscribe-error").style.display="block"}',
'    })();',
'    </script>',
'    <script src="js/main.js" defer></script>',
'</body>',
'</html>',
].join('');

export async function onRequest({ request, env }) {
  var url = new URL(request.url);

  if (request.method === 'GET') {
    return new Response(PAGE_HTML, {
      headers: { 'Content-Type': 'text/html; charset=utf-8' },
    });
  }

  if (request.method !== 'POST') {
    return new Response('Method not allowed', { status: 405 });
  }

  var formData = await request.formData();
  var email = (formData.get('email_address') || '').trim();

  if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
    return Response.redirect('https://www.tcmwellness.xyz/unsubscribe?error=1', 302);
  }

  var resendKey = env.RESEND_API_KEY;
  var from = env.RESEND_FROM || 'Folk Calm <guide@tcmwellness.xyz>';
  var extractEmail = function (s) {
    var m = s.match(/<([^>]+)>/);
    return m ? m[1] : s;
  };
  var notifyEmail = env.NOTIFY_EMAIL || extractEmail(from);

  if (!resendKey) {
    return new Response('Server config error.', { status: 500 });
  }

  try {
    var res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': 'Bearer ' + resendKey,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: from,
        to: [notifyEmail],
        subject: 'Unsubscribe request: ' + email,
        html: [
          '<div style="font-family: Georgia, serif; max-width: 600px; margin: 0 auto; padding: 20px;">',
          '<h2 style="color: #5C3317;">Unsubscribe Request</h2>',
          '<p>The following address has requested to be removed from Folk Calm emails:</p>',
          '<p style="font-size: 18px; font-weight: bold; color: #A0522D;">' + email + '</p>',
          '<p style="color: #6B5B4A;">Please remove this address from your mailing list manually.</p>',
          '<hr style="border: 1px solid #e0d5c5; margin: 24px 0;">',
          '<p style="color: #888; font-size: 12px;">Auto-generated by Folk Calm unsubscribe system.</p>',
          '</div>',
        ].join(''),
      }),
    });

    if (!res.ok) {
      var body = await res.text();
      console.error('Resend error [' + res.status + ']: ' + body);
      return Response.redirect('https://www.tcmwellness.xyz/unsubscribe?error=1', 302);
    }

    return Response.redirect('https://www.tcmwellness.xyz/unsubscribe?sent=1', 302);
  } catch (e) {
    console.error('Unsubscribe error:', e);
    return Response.redirect('https://www.tcmwellness.xyz/unsubscribe?error=1', 302);
  }
}
