export async function onRequest({ request, env }) {
  if (request.method !== 'POST') {
    return Response.redirect('https://tcmwellness.xyz/unsubscribe.html', 302);
  }

  var formData = await request.formData();
  var email = (formData.get('email_address') || '').trim();

  if (!email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
    return Response.redirect('https://tcmwellness.xyz/unsubscribe.html?error=1', 302);
  }

  var resendKey = env.RESEND_API_KEY;
  var from = env.RESEND_FROM || 'Folk Calm <guide@tcmwellness.xyz>';
  var extractEmail = function (s) {
    var m = s.match(/<([^>]+)>/);
    return m ? m[1] : s;
  };
  var notifyEmail = env.NOTIFY_EMAIL || extractEmail(from);

  if (!resendKey) {
    return new Response('Server config error.', { status: 500 });
  }

  try {
    var res = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': 'Bearer ' + resendKey,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: from,
        to: [notifyEmail],
        subject: 'Unsubscribe request: ' + email,
        html: [
          '<div style="font-family: Georgia, serif; max-width: 600px; margin: 0 auto; padding: 20px;">',
          '<h2 style="color: #5C3317;">Unsubscribe Request</h2>',
          '<p>The following address has requested to be removed from Folk Calm emails:</p>',
          '<p style="font-size: 18px; font-weight: bold; color: #A0522D;">' + email + '</p>',
          '<p style="color: #6B5B4A;">Please remove this address from your mailing list manually.</p>',
          '<hr style="border: 1px solid #e0d5c5; margin: 24px 0;">',
          '<p style="color: #888; font-size: 12px;">Auto-generated by Folk Calm unsubscribe system.</p>',
          '</div>',
        ].join(''),
      }),
    });

    if (!res.ok) {
      var body = await res.text();
      console.error('Resend error [' + res.status + ']: ' + body);
      return Response.redirect('https://tcmwellness.xyz/unsubscribe.html?error=1', 302);
    }

    return Response.redirect('https://tcmwellness.xyz/unsubscribe.html?sent=1', 302);
  } catch (e) {
    console.error('Unsubscribe error:', e);
    return Response.redirect('https://tcmwellness.xyz/unsubscribe.html?error=1', 302);
  }
}
